nome= input("Nome do aluno: ")
X= input ("digite a nota 1: ")
Y= input ("digite a nota 2: ")
Z=input ("digite a nota 3: ")
x=int(X)
y=int(Y)
z=int(Z)
R=(x+y+z)
nota=(R/3)
print("A nota final do aluno: ",nome,"e",nota)